#+TITLE: Realising Benefits from Digital Water Meters: Collecting, Storing and Analysing Water Consumption Data
* Introduction
The past few years, more and more water utilities are replacing their traditional manual water meter with data loggers that transmit regular data. These new systems provide about two-thousand times the amount of data of the traditional method of reading the analogue eyeball reads.
Coliban Water decided to develop in-house software 
* Problem statement
** Benefits-Realisation
Given that the vast majority of water utilities are not-for profit organisations, there is no difference between business benefits and customer benefits. [Monks]
*** Direct Customer benefits
*** Indirect customer benefits
** Data needs
A case study illustrates how to decide the ideal amount of data to collect. A water utility discussed how much data they wanted to gather to measure how much water customers use. The existing method only provided one data point for each water meter every three months. The water engineers would ideally like a reading every five minutes, while the billing department was more than happy with one daily reading. 

New technology became available that collects data at a higher frequency. However, the higher the rate, the higher the cost of collection due to transmission bandwidth and battery life. Collecting data every five minutes was considered to be unfeasible and potentially unethical because it reveals too much about the lifestyles of customers. Daily data was insufficient to provide benefits in network design and operation. The utility decided to collect hourly data because it allows for most of the sought benefits, doesn't significantly impact the privacy of customers and is within reasonable reach for the current level of technology.

- Billing: one per day
- Leak detection: 15 per day
- Engineering: 15 per day
** Requirements
- Open system to allow for integration of various sources of digital metering data
- Maximise existing IT infrastructure
- Ability to integrate digital metering intelligence with various other platforms (SCADA, customer portal)
- 

* Solution
** Collection
The data is current collected through secure FTP transmission of CSV files. The data is transmitted hourly to the Coliban Water servers.
** Storage
** Reporting and Analysis
*** Asset Performance
*** Water consumption
** Future Development
*** Sharing the software
Shared under a GNU General Public Licence (GPL) version 3.
* Conclusion
This data creates a new innovation frontier for water utilities. However, collecting and storing data by itself is not sufficient

#+begin_quote
To know and not to do is not yet to know.
#+end_quote
